# workflow 이름
name: ci

# 워크플로우를 실행시키는 event
on: [push]

jobs:
  # 의존성 설치
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Restore node modules from cache
        id: restore-node-modules
        uses: actions/cache@v3
        with:
          path: week-5/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('week-5/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node
  
      - name: Install dependencies
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: npm install
        working-directory: week-5

  # lint 확인 및 수정
  lint:
      runs-on: ubuntu-latest
      needs: install-dependencies
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'

        - name: Restore node modules from cache
          id: restore-node-modules
          uses: actions/cache@v3
          with:
            path: week-5/node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('week-5/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

        - name: Install dependencies (if not cached)
          if: steps.restore-node-modules.outputs.cache-hit != 'true'
          run: npm install
          working-directory: week-5

        - name: Run lint
          run: npm run lint
          working-directory: week-5

  # 테스트 검증
  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Restore node modules from cache
        id: restore-node-modules
        uses: actions/cache@v3
        with:
          path: week-5/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('week-5/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (if not cached)
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: npm install
        working-directory: week-5

      - name: Run tests
        run: npm run test
        working-directory: week-5
  
  # React Build
  build:
    runs-on: ubuntu-latest
    needs: [install-dependencies, lint, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Restore node modules from cache
        id: restore-node-modules
        uses: actions/cache@v3
        with:
          path: week-5/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('week-5/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (if not cached)
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: npm install
        working-directory: week-5

      - name: Run Build
        run: npm run build
        working-directory: week-5
      
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.14.x
          lhci autorun
        working-directory: week-5